### ISSUE TITLE
Blog Links - Code | IT | Future

### ISSUE THREAD

**Issue by raunakUSI** [raunak-r/notes#14]
https://www.deccanherald.com/opinion/whitehat-jr-vs-the-colourful-giraffe-do-children-really-need-to-learn-to-code-934262.html

**Comment by raunak-r** [comment]
#6 

https://microtica.com/blog/everything-about-microservices/

**Comment by raunak-r** [comment]
# Language and Library Wars

https://blog.geekforbrains.com/after-a-year-of-using-nodejs-in-production-78eecef1f65a
https://blog.geekforbrains.com/why-im-switching-from-python-to-nodejs-1fbc17dc797a#.uhtnz6yv1

- Java vs Django (https://lincolnloop.com/portfolio/gamesradar/?fbclid=IwAR3wNCL_rGAighnqkfUrDXrc91MFIrKveZ6Jla8OiWswpT5k7CB7ObroR0M)

**Comment by raunak-r** [comment]
# Website Builders

- https://www.mybestwebsitebuilder.com/compare-wix-vs-wordpress-vs-webflow

**Comment by raunak-r** [comment]
# Future

https://scottbelsky.medium.com/8-themes-for-the-near-future-of-tech-410dbb0b1afb?fbclid=IwAR1nxwN81a_X3C8FJsB2Nc8t8ZgVwAq9BhsfGwHqLxR4HHmdMsE2vEKvkaQ
